# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 521209abf73026d37679d5b835df066f7f7586e07c7c360839e0dc44f3f9ec7d58b1fc3910a65d21feb5025fec53fb0197b125390ce7ea77457a2bcb1f06fea4

test:
  secret_key_base: ed9813321aeeb62a2e65edc41f8797411c361cae2add1f26d20b9f66c2543c8730e136e35a6c558272f62a6e8f1ca5232631f81375e1479bcb5d528e9422719b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
